# Generated by Django 5.2.7 on 2025-10-26 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_devolucion',
            fields=[
                ('id_estado_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='estado_prestamo',
            fields=[
                ('id_estado_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='estado_reserva',
            fields=[
                ('id_estado_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_autenticacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField()),
                ('fecha_inicio_reserva', models.DateTimeField()),
                ('fecha_fin_reserva', models.DateTimeField()),
                ('fecha_devolucion_esperada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateTimeField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('id_estado_devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estado_devolucion')),
                ('id_estado_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.estado_prestamo')),
                ('id_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.herramienta')),
            ],
        ),
    ]
