# Generated by Django 5.2.7 on 2025-10-26 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_estado_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.estado_reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.herramienta'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
