# Generated by Django 5.2.7 on 2025-11-02 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_herramienta_id_estado_and_more'),
        ('operaciones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='id_estado_devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='id_estado_prestamo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_estado_reserva',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_autenticacion',
            new_name='id_reserva',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='id_herramienta',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_devolucion_esperada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_herramienta',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado_devolucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(default='nulo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_esperada',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_herramienta_individual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.herramienta_individual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_tipo_herramienta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.tipo_herramienta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(default='nulo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_tipo_herramienta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.tipo_herramienta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='estado_devolucion',
        ),
        migrations.DeleteModel(
            name='estado_prestamo',
        ),
        migrations.DeleteModel(
            name='estado_reserva',
        ),
    ]
