# Generated by Django 5.2.7 on 2025-11-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(default='Prestamo vencido', max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta', to='operaciones.prestamo')),
            ],
        ),
    ]
