# Generated by Django 5.2.7 on 2025-12-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_tipo_herramienta_imagen_url'),
        ('operaciones', '0007_prestamo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado_devolucion',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Defectuoso', 'Defectuoso'), ('Dañado', 'Dañado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Vencido', 'Vencido'), ('Cancelado', 'Cancelado')], default='Activo', max_length=50),
        ),
        migrations.CreateModel(
            name='prestamoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_herramienta_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='inventario.herramienta_individual')),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_herramientas', to='operaciones.prestamo')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='herramientas',
            field=models.ManyToManyField(related_name='prestamos_asociados', through='operaciones.prestamoHerramienta', to='inventario.herramienta_individual'),
        ),
    ]
