# Generated by Django 5.2.7 on 2025-12-09 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_tipo_herramienta_imagen_url'),
        ('operaciones', '0008_alter_prestamo_estado_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='herramientas',
            field=models.ManyToManyField(related_name='reservas_asociadas', to='inventario.herramienta_individual'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id_herramienta_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.herramienta_individual'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id_tipo_herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_tipo_herramienta', to='inventario.tipo_herramienta'),
        ),
    ]
