# Generated by Django 5.2.7 on 2025-12-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_herramienta_individual_disponible_and_more'),
        ('operaciones', '0009_reserva_herramientas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='id_tipo_herramienta',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Expirado', 'Expirado'), ('Entregado', 'Entregado'), ('Finalizado', 'Finalizado'), ('Vencido', 'Vencido'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='herramientas',
            field=models.ManyToManyField(blank=True, null=True, related_name='prestamos_asociados', through='operaciones.prestamoHerramienta', to='inventario.herramienta_individual'),
        ),
        migrations.CreateModel(
            name='PrestamoTipoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_prestamo', to='operaciones.prestamo')),
                ('tipo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_por_tipo', to='inventario.tipo_herramienta')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipos_herramienta',
            field=models.ManyToManyField(related_name='prestamos_tipo_herramienta', through='operaciones.PrestamoTipoHerramienta', to='inventario.tipo_herramienta'),
        ),
    ]
