# Generated by Django 5.2.7 on 2025-12-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_remove_prestamo_id_tipo_herramienta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='archivada',
            field=models.BooleanField(default=False),
        ),
    ]

