# Generated by Django 5.2.7 on 2026-05-22 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_herramienta_individual_fecha_mantencion'),
        ('operaciones', '0013_prestamo_turnero_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_mantencion', to='inventario.herramienta_individual'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('Prestamo', 'Préstamo'), ('Mantencion', 'Mantención')], default='Prestamo', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='prestamo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerta', to='operaciones.prestamo'),
        ),
    ]
