# Generated by Django 5.2.7 on 2025-10-26 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_herramienta',
            fields=[
                ('id_categoria_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estado_herramienta',
            fields=[
                ('id_estado_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='herramienta',
            fields=[
                ('id_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria_herramienta')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estado_herramienta')),
            ],
        ),
    ]
