# Generated by Django 5.2.7 on 2025-11-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='id_categoria',
        ),
        migrations.RenameField(
            model_name='categoria_herramienta',
            old_name='id_categoria_herramienta',
            new_name='id_categoria',
        ),
        migrations.CreateModel(
            name='tipo_herramienta',
            fields=[
                ('id_tipo_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen_url', models.CharField(max_length=200)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria_herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='herramienta_individual',
            fields=[
                ('id_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('estado_herramienta', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateTimeField()),
                ('id_tipo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tipo_herramienta')),
            ],
        ),
        migrations.DeleteModel(
            name='estado_herramienta',
        ),
    ]
