# Generated by Django 5.2.7 on 2025-11-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_herramienta_id_estado_and_more'),
        ('operaciones', '0003_remove_prestamo_id_estado_devolucion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='herramienta',
        ),
    ]
