# Generated by Django 5.2.7 on 2025-11-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_delete_herramienta'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta_individual',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='herramientas/'),
        ),
    ]
