# Generated by Django 5.2.7 on 2025-11-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_herramienta_individual_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta_individual',
            name='estado_herramienta',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Defectuoso', 'Defectuoso'), ('Dañado', 'Dañado')], max_length=50),
        ),
    ]
