# Generated by Django 5.2.7 on 2025-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_herramienta_individual_estado_herramienta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_herramienta',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='tipos_herramienta/'),
        ),
    ]
