# Generated by Django 5.2.7 on 2025-12-13 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_tipo_herramienta_imagen'),
        ('operaciones', '0009_reserva_herramientas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta_individual',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipo_herramienta',
            name='reservado',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='tipo_herramienta',
            name='stock',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='historial_herramienta',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('estado_herramienta', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Defectuoso', 'Defectuoso'), ('Dañado', 'Dañado')], max_length=50)),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.herramienta_individual')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_herramientas', to='operaciones.prestamo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
