# Generated by Django 5.2.7 on 2026-05-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_herramienta_individual_numero_prestamos'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta_individual',
            name='fecha_mantencion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
