# Generated by Django 5.2.7 on 2025-11-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_first_name_remove_usuario_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='carrera',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.carrera'),
        ),
    ]
