# Generated by Django 5.2.7 on 2025-11-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_carrera_remove_usuario_carrera_usuario_id_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/'),
        ),
    ]
