# Generated by Django 5.2.7 on 2025-11-13 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
