# Generated by Django 5.2.7 on 2025-11-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_foto_remove_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
